# Generated by Django 6.0.1 on 2026-06-07 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(default='About Us', max_length=120)),
                ('title', models.CharField(default='A professional distribution and warehouse partner in Oman.', max_length=240)),
                ('overview', models.TextField(default='Muttrah Pharmacy supports healthcare procurement teams with a focused catalog of pharmaceutical, orthopedic, and medical supply products.')),
                ('mission_title', models.CharField(default='Mission', max_length=220)),
                ('mission_text', models.TextField(default='Make critical product sourcing clear, reliable, and responsive.')),
                ('vision_title', models.CharField(default='Vision', max_length=220)),
                ('vision_text', models.TextField(default='Become a leading medical distribution reference for Oman.')),
                ('warehouse_title', models.CharField(default='Warehouse Information', max_length=180)),
                ('warehouse_text', models.TextField(default='Organized product storage and catalog-backed distribution readiness.')),
                ('network_title', models.CharField(default='Distribution Network', max_length=180)),
                ('network_text', models.TextField(default='Supply support for pharmacies, clinics, hospitals, and orthopedic providers.')),
                ('why_title', models.CharField(default='Why Choose Us', max_length=180)),
                ('why_text', models.TextField(default='Focused medical category knowledge with direct inquiry channels.')),
                ('brands_eyebrow', models.CharField(default='Brands We Represent', max_length=120)),
                ('brands_title', models.CharField(default='Company data loaded from the API', max_length=220)),
                ('timeline_eyebrow', models.CharField(default='Company Growth Timeline', max_length=120)),
                ('timeline_title', models.CharField(default='Built around practical distribution milestones.', max_length=220)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(default='Contact Us', max_length=120)),
                ('title', models.CharField(default='Send a product or distribution inquiry', max_length=220)),
                ('description', models.TextField(default='Use the form below to post directly to the Django contact API.')),
                ('address_label', models.CharField(default='Address', max_length=80)),
                ('address', models.CharField(default='Muttrah, Muscat, Sultanate of Oman', max_length=240)),
                ('email_label', models.CharField(default='Email', max_length=80)),
                ('email', models.EmailField(default='info@muttrahpharmacy.com', max_length=254)),
                ('phone_label', models.CharField(default='Phone', max_length=80)),
                ('phone', models.CharField(default='+968 0000 0000', max_length=80)),
                ('map_title', models.CharField(default='Muttrah, Muscat', max_length=160)),
                ('map_description', models.TextField(default='Map embed placeholder ready for your Google Maps iframe.')),
                ('google_maps_embed_url', models.URLField(blank=True)),
                ('form_button_label', models.CharField(default='Submit Inquiry', max_length=80)),
            ],
            options={
                'verbose_name': 'Contact Page Content',
                'verbose_name_plural': 'Contact Page Content',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=80)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_eyebrow', models.CharField(default='Pharmaceutical and orthopedic distributor in Oman', max_length=180)),
                ('hero_title', models.CharField(default='Muttrah Pharmacy', max_length=180)),
                ('hero_description', models.TextField(default='A dependable warehouse partner for pharmacies, clinics, hospitals, and orthopedic teams sourcing quality medical products across Oman.')),
                ('primary_button_label', models.CharField(default='Browse Products', max_length=80)),
                ('secondary_button_label', models.CharField(default='Contact Sales', max_length=80)),
                ('intro_eyebrow', models.CharField(default='Company Introduction', max_length=120)),
                ('intro_title', models.CharField(default='Built for dependable medical product distribution.', max_length=220)),
                ('brands_eyebrow', models.CharField(default='Featured Brands', max_length=120)),
                ('brands_title', models.CharField(default='Brands represented in the live catalog', max_length=220)),
                ('categories_eyebrow', models.CharField(default='Product Categories', max_length=120)),
                ('categories_title', models.CharField(default='Organized for fast sourcing', max_length=220)),
                ('cta_eyebrow', models.CharField(default='Ready to source', max_length=120)),
                ('cta_title', models.CharField(default='Connect with Muttrah Pharmacy today.', max_length=220)),
                ('cta_button_label', models.CharField(default='Send Inquiry', max_length=80)),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
        ),
        migrations.CreateModel(
            name='AboutTimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_items', to='website.aboutpage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(default='A practical operating model for procurement teams that need clear catalog access and fast communication.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='website.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
