# Generated by Django 6.0.5 on 2026-06-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_seed_default_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='brands_description',
            field=models.TextField(default='Muttrah Pharmacy partners with internationally recognized healthcare and orthopedic brands to deliver high-quality products and trusted medical solutions across Oman. Our portfolio includes leading manufacturers specializing in pharmaceuticals, orthopedic care, rehabilitation, and healthcare supplies.'),
        ),
    ]
