# Generated by Django 6.0.5 on 2026-06-09 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_homepage_brands_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='trust_eyebrow',
            field=models.CharField(default='Why Choose Us', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='trust_title',
            field=models.CharField(default='Why Healthcare Professionals Trust Muttrah Pharmacy', max_length=220),
        ),
        migrations.CreateModel(
            name='HomeTrustItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_items', to='website.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
