# Generated by Django 6.0.1 on 2026-06-12 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_footercontent_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_hero/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_images', to='website.aboutpage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
