# Generated by Django 6.0.1 on 2026-06-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_aboutheroimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='inquiry_recipient_email',
            field=models.EmailField(default='jansabithjans@gmail.com', help_text='Email address where contact form submissions will be sent.', max_length=254),
        ),
    ]
