# Generated by Django 6.0.1 on 2026-06-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_contactpage_inquiry_recipient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='location_description',
            field=models.TextField(default='Our headquarters and main distribution center are strategically located to serve the healthcare community efficiently.'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='location_eyebrow',
            field=models.CharField(default='Our Location', max_length=120),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='location_map_url',
            field=models.URLField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3655.70020525746!2d58.542142999999996!3d23.615082400000002!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e91f900164bdb5b%3A0x1c2403fc0d8bf5e1!2sMUTTRAH%20PHARMACY!5e1!3m2!1sen!2sin!4v1781096686549!5m2!1sen!2sin', max_length=500),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='location_title',
            field=models.CharField(default='Visit Us in Muttrah', max_length=220),
        ),
    ]
