# Generated by Django 6.0.5 on 2026-09-29 16:24

from django.db import migrations, models

OLD_DESCRIPTION = "Use the form below to post directly to the Django contact API."
NEW_DESCRIPTION = "Reach Muttrah Pharmacy for product availability, pricing, and distribution inquiries."


def replace_form_description(apps, schema_editor):
    ContactPage = apps.get_model('website', 'ContactPage')
    ContactPage.objects.filter(description=OLD_DESCRIPTION).update(description=NEW_DESCRIPTION)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_aboutpage_location_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSubmission',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='form_button_label',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='inquiry_recipient_email',
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='description',
            field=models.TextField(default='Reach Muttrah Pharmacy for product availability, pricing, and distribution inquiries.'),
        ),
        migrations.RunPython(replace_form_description, migrations.RunPython.noop),
    ]
