# Generated by Django 6.0.5 on 2026-09-30 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_contact_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Wide landscape image, at least 1920 x 1080 px.', upload_to='home_hero/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Optional tall image for phones (for example 1080 x 1350 px). The main image is used if empty.', upload_to='home_hero/mobile/')),
                ('alt_text', models.CharField(blank=True, help_text='Short description of the image for accessibility and SEO.', max_length=180)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='website.homepage')),
            ],
            options={
                'verbose_name': 'Hero slide',
                'verbose_name_plural': 'Hero slides',
                'ordering': ['order', 'id'],
            },
        ),
    ]
