# Generated by Django 6.0.1 on 2026-06-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_aboutpage_meta_description_aboutpage_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='whatsapp_number',
            field=models.CharField(default='96899793939', help_text='WhatsApp number for contact buttons (e.g., 96899793939)', max_length=20),
        ),
    ]
