# Generated by Django 6.0.5 on 2026-09-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_homeheroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeheroslide',
            name='tablet_image',
            field=models.ImageField(blank=True, help_text='Optional. Tablets (768 to 1279 px wide). Recommended 1536 x 1152 px, 4:3. Uses the desktop image if empty.', upload_to='home_hero/tablet/'),
        ),
        migrations.AlterField(
            model_name='homeheroslide',
            name='image',
            field=models.ImageField(help_text='Required. Laptops and desktops (1280 px and wider). Recommended 1920 x 1080 px, landscape 16:9.', upload_to='home_hero/', verbose_name='Desktop image'),
        ),
        migrations.AlterField(
            model_name='homeheroslide',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Optional. Phones (below 768 px wide). Recommended 1080 x 1920 px, portrait 9:16. Uses the tablet or desktop image if empty.', upload_to='home_hero/mobile/'),
        ),
    ]
