# Generated by Django 6.0.5 on 2026-09-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_homeheroslide_tablet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeheroslide',
            name='focus',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='top', help_text='Which part of the image stays visible when the screen crops it.', max_length=10),
        ),
    ]
