# Generated by Django 6.0.5 on 2026-09-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_homeheroslide_focus_default_bottom'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeheroslide',
            name='display',
            field=models.CharField(choices=[('cover', 'Fill screen (may crop edges)'), ('contain', 'Show whole image (never crops)')], default='cover', help_text='Fill screen suits wide lifestyle photos. Show whole image suits product boxes, packaging, logos or text - the full image sits on the right over a blurred copy of itself.', max_length=10),
        ),
        migrations.AlterField(
            model_name='homeheroslide',
            name='focus',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='bottom', help_text="Only for 'Fill screen': which part of the image stays visible when the screen crops it.", max_length=10),
        ),
    ]
