# Generated by Django 6.0.5 on 2026-10-01 18:29

from django.db import migrations, models


# Existing features get icons matching their position (trophy, people, box, truck)
DEFAULT_ICONS = ["trophy", "people", "box", "truck"]


def assign_feature_icons(apps, schema_editor):
    HomeFeature = apps.get_model("website", "HomeFeature")
    for feature, icon in zip(HomeFeature.objects.order_by("order", "id"), DEFAULT_ICONS):
        feature.icon = icon
        feature.save(update_fields=["icon"])


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_homeheroslide_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='homefeature',
            name='icon',
            field=models.CharField(choices=[('trophy', 'Trophy'), ('people', 'People / Team'), ('box', 'Box / Package'), ('truck', 'Delivery Truck'), ('shield', 'Shield'), ('heart', 'Heart')], default='trophy', help_text='Icon shown next to the title in the Company Introduction section.', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_description',
            field=models.TextField(blank=True, default='We are a leading supplier of pharmaceutical products, orthopedic solutions, rehabilitation aids, surgical supplies, and healthcare equipment, committed to supporting hospitals, clinics, and customers across Oman.'),
        ),
        migrations.RunPython(assign_feature_icons, migrations.RunPython.noop),
    ]
