# Generated by Django 6.0.5 on 2026-10-01 19:15

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_TABS = [
    ("best_sellers", "Best Sellers", "Our most popular products, trusted by customers across Oman", 1),
    ("featured", "Featured", "Shop our most popular solutions", 2),
    ("new_launches", "New Launches", "The latest additions to our range", 3),
]


def create_showcase_tabs(apps, schema_editor):
    ShowcaseTab = apps.get_model("website", "ShowcaseTab")
    for key, name, subtitle, order in DEFAULT_TABS:
        ShowcaseTab.objects.get_or_create(
            key=key,
            defaults={"name": name, "subtitle": subtitle, "order": order},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_seo_fields_updated_at'),
        ('website', '0016_homepage_intro_description_homefeature_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='1 shows first.', verbose_name='Position')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Product in this tab',
                'verbose_name_plural': 'Products in this tab - set their order',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('best_sellers', 'Best Sellers'), ('featured', 'Featured'), ('new_launches', 'New Launches')], editable=False, max_length=20, unique=True)),
                ('name', models.CharField(help_text='Text on the tab button and the section heading, e.g. Best Sellers.', max_length=60, verbose_name='Tab name')),
                ('subtitle', models.CharField(blank=True, help_text='Short line under the heading while this tab is open.', max_length=220)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide this tab on the website without removing its products.', verbose_name='Show tab')),
                ('order', models.PositiveIntegerField(default=0, help_text='Position of the tab button. 1 is the first button.', verbose_name='Tab position')),
                ('products', models.ManyToManyField(blank=True, related_name='showcase_tabs', through='website.ShowcaseItem', to='products.product')),
            ],
            options={
                'verbose_name': 'Home product showcase tab',
                'verbose_name_plural': 'Home product showcase',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='showcaseitem',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.showcasetab'),
        ),
        migrations.AddConstraint(
            model_name='showcaseitem',
            constraint=models.UniqueConstraint(fields=('tab', 'product'), name='unique_showcase_tab_product'),
        ),
        migrations.RunPython(create_showcase_tabs, migrations.RunPython.noop),
    ]
