# Generated by Django 6.0.5 on 2026-10-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_home_product_showcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='footercontent',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Optional. Shown behind the whole footer, full width on every screen size, with a dark shade over it so the text stays readable. A wide landscape photo works best, around 1920 x 800 px.', upload_to='footer/'),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='background_shade',
            field=models.CharField(choices=[('light', 'Light - image clearly visible'), ('medium', 'Medium'), ('strong', 'Strong - image very subtle')], default='medium', help_text='How dark the shade over the background image is.', max_length=10, verbose_name='Background shade'),
        ),
    ]
