# Generated by Django 6.0.5 on 2026-10-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_footer_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='footercontent',
            name='email_2',
            field=models.EmailField(blank=True, help_text='Optional. Shown under the first email in the footer.', max_length=254, verbose_name='Second email'),
        ),
    ]
