# Generated by Django 6.0.5 on 2026-10-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_footer_second_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='email_2',
            field=models.EmailField(blank=True, help_text='Optional. Shown under the first email.', max_length=254, verbose_name='Second email'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone_2',
            field=models.CharField(blank=True, help_text='Optional. Shown under the first phone number.', max_length=80, verbose_name='Second phone'),
        ),
    ]
