# Generated by Codex on 2026-06-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_company'),
        ('companies', '0002_companyline'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='company_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='companies.companyline'),
        ),
    ]
