# Generated by Codex on 2026-06-08

import django.db.models.deletion
from django.db import migrations, models


def create_tynor_lines(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    CompanyLine = apps.get_model('companies', 'CompanyLine')

    tynor = Company.objects.filter(name__iexact='TYNOR').first()
    if not tynor:
        return

    for index, name in enumerate(['TYNOR LIFE', 'TYNOR SPORT'], start=1):
        CompanyLine.objects.get_or_create(
            company=tynor,
            name=name,
            defaults={
                'display_order': index * 10,
                'is_active': True,
            }
        )


def remove_tynor_lines(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    CompanyLine = apps.get_model('companies', 'CompanyLine')

    tynor = Company.objects.filter(name__iexact='TYNOR').first()
    if not tynor:
        return

    CompanyLine.objects.filter(
        company=tynor,
        name__in=['TYNOR LIFE', 'TYNOR SPORT']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='companies.company')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='companyline',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_company_line_name'),
        ),
        migrations.RunPython(create_tynor_lines, remove_tynor_lines),
    ]
