# Generated by Django 6.0.5 on 2026-10-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyline'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Brand logo shown on the home page. A PNG with a transparent background works best, around 400 x 200 px.', upload_to='company_logos/'),
        ),
    ]
