# Generated by Django 6.0.5 on 2026-10-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='companyline',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
    ]
