# Generated by Django 6.0.5 on 2026-09-29 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', 'id']},
        ),
    ]
