# Generated by Django 6.0.5 on 2026-10-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_seo_fields_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Products without a main image are hidden on the website.', upload_to='products/', verbose_name='Main image'),
        ),
    ]
