# Generated by Django 6.0.5 on 2026-10-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_image_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Optional. What this photo shows, e.g. "TYNOR Knee Cap Air side view". Leave empty to use the brand and product name.', max_length=160, verbose_name='Alt text'),
        ),
    ]
